### ISSUE TITLE
The <template> element is deprecated

### ISSUE THREAD

**Issue by moshmage** [angular-starter-kit/generator-ngx-app#58]
Seems like ngx-app is using the old `<template>` tag which was deprecated recently in favour of `ng-template`

Reproducing:
- `npm install -g yo generator-ngx-app && yo ngx-app`
- open the `localhost:4200`
- open console
- refresh to get a new set of warnings (it shows after the `[App] init` from the `logger.service.ts`

**Comment by sinedied** [comment]
Thanks for reporting the issue!
However this is not directly related to the the generator's template as we do not use the `<template>` tag, but this is due to the `ng-bootstrap` dependency, see this issue: https://github.com/ng-bootstrap/ng-bootstrap/issues/1337

They are working on in, and having the warning removed should be just a matter of `npm update` after they release a new version.
